name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python -V


      - name: Validate Repository
        run: make validate

      - name: Check DCO sign-off
        shell: bash
        run: |
          RANGE="origin/${{ github.base_ref }}..HEAD"
          for c in $(git rev-list "$RANGE"); do
            if ! git log -1 --format=%B "$c" | grep -q "Signed-off-by:"; then
              echo "::error::Commit $c missing DCO sign-off ('Signed-off-by:')"
              exit 1
            fi
          done
          echo "All commits include DCO sign-off."
